### PR TITLE
fix: another clobbering issue

### LINKED ISSUE #1061: Had a clobber
Once more I hit a clobber ... 

I need to take another look (this came when setting up the pixi environment):

```
Error: 
  × failed to unclobber clobbered files
  ├─▶ failed to rename lib/gcc/arm64-apple-darwin20.0.0/13.2.0/include/ISO_Fortran_binding.h__clobber-from-gfortran_impl_osx-arm64 to lib/gcc/arm64-apple-
  │   darwin20.0.0/13.2.0/include/ISO_Fortran_binding.h
  ╰─▶ failed to rename file from /Users/wolfv/Programs/pixi/.pixi/envs/default/lib/gcc/arm64-apple-darwin20.0.0/13.2.0/include/ISO_Fortran_binding.h__clobber-
      from-gfortran_impl_osx-arm64 to /Users/wolfv/Programs/pixi/.pixi/envs/default/lib/gcc/arm64-apple-darwin20.0.0/13.2.0/include/ISO_Fortran_binding.h: No
      such file or directory (os error 2)
```

### PR DESCRIPTION
**Pull request by wolfv**
This should fix #1061

### CODE REVIEW

File: crates/rattler-bin/src/commands/create.rs [hunk 1]
```diff
@@ -271,6 +271,16 @@ pub async fn create(opt: Opt) -> anyhow::Result<()> {
 
     let required_packages: Vec<RepoDataRecord> = solver_result.records;
 
+    let no_deps = false;
```
Comment (baszalmstra) [inline crates/rattler-bin/src/commands/create.rs:274]: Should this be removed?

File: crates/rattler/src/install/mod.rs [hunk 2]
```diff
@@ -328,16 +333,25 @@ pub async fn link_package(
...
+            let clobber_path = clobber_paths.get(&entry.relative_path).cloned();
+            LinkPath {
+                entry,
+                computed_path,
+                clobber_path,
+            }
+        })
+        .collect();
+
+    // drop(clobber_paths);
```
Comment (baszalmstra) [inline crates/rattler/src/install/mod.rs:349]: Remove?

File: crates/rattler/src/install/mod.rs [hunk 3]
```diff
@@ -639,25 +655,32 @@ pub fn link_package_sync(
...
+        let clobber_path = clobber_paths.get(&entry.relative_path).cloned();
+        LinkPath {
+            entry,
+            computed_path,
+            clobber_path,
         }
-    }
+    });
+
+    // We can already drop this
```
Comment (baszalmstra) [inline crates/rattler/src/install/mod.rs:676]: Remove?

File: crates/rattler/src/install/mod.rs [hunk 4]
```diff
@@ -737,19 +760,20 @@ pub fn link_package_sync(
         // files that are either in the clobber map or contain a placeholder,
         // we defer to the regular linking that comes after this block
         // and re-add them to the paths_by_directory map
-        for file in files {
-            if clobber_paths.contains_key(&file.1) || file.0.prefix_placeholder.is_some() {
```
Comment (wolfv) [inline crates/rattler/src/install/mod.rs:741]: The problem was that we were using the computed path here, which already contained the "clobber"-modifications. And thus, we never re-added the path here...

File: crates/rattler-bin/src/commands/create.rs (hunk 1 above)
Comment (wolfv) [reply crates/rattler-bin/src/commands/create.rs]: Removed all changes to this file.
